### PR TITLE
Fix evaluate mode toggle to no longer break project editing

### LINKED ISSUE #660: Toggling Evaluate mode breaks project editing for all but top-level (e.g. county) geounits
GIF shows this w/ Dane County & blocks, but this also happened w/ PA & block groups / blocks.

output

### PR DESCRIPTION
**Pull request by kevinearldenny**
## Overview

- Fix bug identified in #660 around toggling evaluate mode breaking project editing for lower-level geounits
- Hides editing tools when in evaluate mode
- Hides legend when not in evaluate mode

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

- Open a project, and select 'Block group' editing level
- Toggle editing mode and select a view (e.g., compactness)
- Expect: Cursor becomes the map pan tool when in evaluate mode
- Turn evaluate mode off
- Expect: You are able to edit the project at the Block group level after opening evaluate mode

Closes #660

### CODE REVIEW

File: src/client/components/map/Map.tsx [hunk 1]
```diff
@@ -305,15 +308,24 @@ const DistrictsMap = ({
...
+            map.setLayoutProperty(
+              levelToSelectionLayerId(geoLevel.id),
+              "visibility",
+              idx >= invertedGeoLevelIndex ? "visible" : "none"
+            );
           }
+          map.setLayoutProperty(
+            levelToLineLayerId(geoLevel.id),
+            "visibility",
+            idx >= invertedGeoLevelIndex ? "visible" : "none"
```
Comment (pcaisse) [inline src/client/components/map/Map.tsx:323]: Since this is duplicated I'd break it out as something like:
```ts
const geoLevelVisibility = idx >= invertedGeoLevelIndex ? "visible" : "none"
```
and use it in both places.

File: src/client/components/map/Map.tsx [hunk 2]
```diff
@@ -305,15 +308,24 @@ const DistrictsMap = ({
         map.setLayoutProperty(TOPMOST_GEOLEVEL_EVALUATE_SPLIT_ID, "visibility", "none");
         map.setLayoutProperty(TOPMOST_GEOLEVEL_EVALUATE_FILL_SPLIT_ID, "visibility", "none");
         map.setLayoutProperty(DISTRICTS_CONTIGUITY_CHLOROPLETH_LAYER_ID, "visibility", "none");
+        const invertedGeoLevelIndex = staticMetadata.geoLevelHierarchy.length - geoLevelIndex - 1;
         staticMetadata.geoLevelHierarchy.forEach((geoLevel, idx) => {
-          if (idx === staticMetadata.geoLevelHierarchy.length - 1) {
-            map.setLayoutProperty(levelToLineLayerId(geoLevel.id), "visibility", "visible");
-            map.setLayoutProperty(levelToSelectionLayerId(geoLevel.id), "visibility", "visible");
+          if (!evaluateMode) {
```
Comment (pcaisse) [inline src/client/components/map/Map.tsx:313]: I'm not sure I fully understand this conditional. Why do we want to avoid toggling geolevel visibility for only selection layers when not in evaluate mode?

**Review by pcaisse — APPROVED** [review]
Tested well. Left a couple of comments.

File: src/client/components/map/Map.tsx (hunk 2 above)
Comment (kevinearldenny) [reply src/client/components/map/Map.tsx:313]: I'm not entirely sure, tbh. Seems to work fine after removing
