### PR TITLE
Fix find menu button so it properly opens the find menu

### LINKED ISSUE #859: Find menu doesn't open
Trying to open the Find Unassigned / Fin non-contiguous menu no longer works

I think this was broken by https://github.com/PublicMapping/districtbuilder/pull/835

### PR DESCRIPTION
**Pull request by kevinearldenny**
## Overview

- Fixes the bug identified in #859 around the find menu not opening
- Toggles the paintbrush size slider when the paintbrush icon is clicked 

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

image

### Notes

It seemed like putting this on the right side was the _easiest_ solution here, but I'm not necessarily sure if it's the best solution from a UX perspective. Perhaps @jfrankl might have a better solution for how to make this more visually apparent / usable

## Testing Instructions

- Open a project
- Click the find menu; expect the find menu to appear

Closes #859

### CODE REVIEW

File: src/client/components/MapHeader.tsx [hunk 1]
```diff
@@ -285,7 +289,7 @@ const MapHeader = ({
         )}
         <Flex className="geolevel-button-group">{geoLevelOptions}</Flex>
       </Flex>
-      <Box sx={{ lineHeight: "1" }}>
+      <Box sx={{ lineHeight: "1", position: "fixed", right: "150px" }}>
```
Comment (maurizi) [inline src/client/components/MapHeader.tsx:292]: It's very rare that you want `position: "fixed";` - you almost always want  `position: "absolute";` instead (the exception that proves the rule is clarifying here: an element that is intended to remain fixed when the page scrolls _and_ be overlaid above normal page content, like a floating "Help" button, is a good candidate for using `position: "fixed";`).

`"fixed"` means absolute positioning in regards to the _viewport_, whereas `"absolute"` means absolute positioning in regards to the parent element (or parent's parent, etc.).

In particular for this case, this would mean that by using `"fixed"` positioning our styling would break if the header above this button changes height, whereas using `"absolute"` positioning it will not.

```suggestion
      <Box sx={{ lineHeight: "1", position: "absolute", right: "150px" }}>
```

File: src/client/components/MapHeader.tsx [hunk 2]
```diff
@@ -307,6 +311,23 @@ const MapHeader = ({
           </Select>
         </Flex>
       </Box>
+      <Box sx={{ position: "relative", mr: "5px" }}>
+        <Button
+          sx={{ ...style.selectionButton }}
+          // eslint-disable-next-line
+          onClick={() => store.dispatch(toggleFind(!findMenuOpen))}
```
Comment (maurizi) [inline src/client/components/MapHeader.tsx:318]: This is a cleaner way to fix the lint error:
```suggestion
          onClick={() => {
            store.dispatch(toggleFind(!findMenuOpen));
          }
```

File: src/client/components/MapHeader.tsx [hunk 3]
```diff
@@ -307,6 +311,23 @@ const MapHeader = ({
...
+        >
+          <Box
+            sx={{
+              borderBottom: findMenuOpen ? "solid 1px" : "none",
+              borderBottomColor: "muted",
```
Comment (maurizi) [inline src/client/components/MapHeader.tsx:324]: The white-on-white isn't showing up here - consider either switching to a dark border:
```suggestion
              borderBottomColor: "muted",
```

Comment (kevinearldenny) [reply src/client/components/MapHeader.tsx:324]: Good catch.

**Review by maurizi — APPROVED** [review]
I can find things again 🎉
