### PR TITLE
Don't create a new map when joining an organization

### LINKED ISSUE #662: New map gets created when joining organization
## Description
Clicking "Join organization" after viewing a modal from "Use this template" will create a new map.

## Steps To Reproduce

1. Go to an organization page
2. "Leave organization" if you are already a member
3. Click "Use this template" for any of the templates
4. When the modal appears, press "Back"
5. Click "Join organization"

## Expected behavior
The organization is joined. Nothing else happens.

## Actual behavior

The organization is joined a new map is created for the template clicked on before.

## Your environment

 - OS: macOS
 - Browser: Chrome
 - Version: 88.0.4324.192

### PR DESCRIPTION
**Pull request by kevinearldenny**
## Overview

Fixes a bug around projects being created when a user clicks 'Use template' on a project template after having left an an organization, and then rejoins (as initially identified by @jfrankl in #662)

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

Optional. Screenshots, examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- Login with a non-admin user who is a member of an organization
- Navigate to the organization screen, and leave an organization
- Click the 'Use template' button on a project template
- Click 'Cancel' on the ensuing dialog
- Click Join Organization; expect the organization to be joined, and no project to be created

Closes #662

### CODE REVIEW

File: src/client/components/JoinOrganizationModal.tsx [hunk 1]
```diff
@@ -59,7 +61,11 @@ const JoinOrganizationModal = ({
     >
       <Box sx={style.modal}>
```
Comment (maurizi) [inline src/client/components/JoinOrganizationModal.tsx:62]: You need to make a small change just above this line to also handle cases where the modal is closed by using the ESC key or clicking on the backdrop:
```diff
diff --git a/src/client/components/JoinOrganizationModal.tsx b/src/client/components/JoinOrganizationModal.tsx
index 94377f9..3ec8bce 100644
--- a/src/client/components/JoinOrganizationModal.tsx
+++ b/src/client/components/JoinOrganizationModal.tsx
@@ -49,7 +49,10 @@ const JoinOrganizationModal = ({
   readonly projectTemplate?: CreateProjectData;
   readonly onCancel: () => void;
 }) => {
-  const hideModal = () => store.dispatch(showCopyMapModal(false));
+  const hideModal = () => {
+    onCancel();
+    store.dispatch(showCopyMapModal(false));
+  };
 
   return showModal ? (
     <AriaModal
```

**Review by maurizi — APPROVED** [review]
