### PR TITLE
Fix bounds for AK mini-map

### LINKED ISSUE #992: Alaska mini-map bounds are off
image

# Notes
 For the main map we use the `bounds` specified in `static-metadata.json` for the region. We don't currently download the `static-metadata.json` for the mini-map display _or_ use it server-side, but we _do_ have it available in-memory on the server as part of the `TopologyService` so it might make sense to attach a `bounds` property to the data returned by the project list pages.

### PR DESCRIPTION
**Pull request by rachelekm**
## Overview

This PR fixes the incorrect bounds generated for the Alaska mini-map displayed on the home screen. This error was initially caused by an issue with the `@turf/bbox` module—the output for `bbox` included incorrect longitudes coordinates for Alaska’s bounding box, assumed to be an issue with the geojson spanning the anti-meridian. For a more reliable fix, this PR instead uses the static bounds specified in `static-metadata.json`, similar to the main map for a project.

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo

Screen Shot 2022-02-16 at 11 39 46 AM

### Notes

The notes of Issue #992 mention that, since the `static-metadata.json` is available in-memory as part of `TopologyService`, it might be worth creating a `bounds` property that can be sent back for mini-map generation. However, we recently got rid of archived topology layers within `TopologyService`, which means this would not be an available option for any projects with archived regions. To accommodate archived projects, the `s3URI` property is attached to the data returned to project list pages instead, which is then used by `fetchStaticMetadata` in a memoized function for each project. While `static-metadata.json` is small, if we want to free up some space we could potentially create the `bounds` property using `TopologyService` by default and return `s3URI` instead for projects that are archived?

## Testing Instructions

- `scripts/server`
- Create a project for `AK`
- Confirm the mini-map bounds are correct on home screen and the community maps page

Closes #992

### CODE REVIEW

File: src/client/components/map/ProjectDistrictsMap.tsx [hunk 1]
```diff
@@ -35,13 +33,21 @@ const ProjectDistrictsMap = ({
 }) => {
   const mapRef = useRef<HTMLDivElement>(null);
   const [mapLoaded, setMapLoaded] = useState<boolean>(false);
+  const [bounds, setBounds] = useState<[number, number, number, number] | null>(null);
+  project.regionConfig &&
+    !bounds &&
+    fetchMemoizedStateBbox(project.regionConfig).then((bboxData: IStaticMetadata["bbox"]) => {
+      // Conversion from readonly -> mutable to match Mapbox interface
+      const [b0, b1, b2, b3] = bboxData;
+      setBounds([b0, b1, b2, b3]);
```
Comment (maurizi) [inline src/client/components/map/ProjectDistrictsMap.tsx:42]: This would work as well to go from read-only -> mutable, and is less brittle (it doesn't need to know what the structure of `bboxData` is:
```suggestion
      setBounds([...bboxData]);
```

File: src/client/api.ts [hunk 2]
```diff
@@ -403,6 +405,16 @@ export async function fetchOrganizationFeaturedProjects(
   });
 }
 
+export const fetchMemoizedStateBbox = memoize(
+  async (region: IRegionConfig): Promise<IStaticMetadata["bbox"]> => {
+    const staticMetadata = await fetchStaticMetadata(region.s3URI);
+    return staticMetadata.bbox;
+  },
+  {
+    normalizer: (args: [region: IRegionConfig]) => JSON.stringify(args[0].name)
```
Comment (maurizi) [inline src/client/api.ts:414]: `RegionConfig.name` is not required to be unique (https://github.com/PublicMapping/districtbuilder/blob/334331cddc6d2c9860699917fc02ada3ccbd4a74/src/server/src/region-configs/entities/region-config.entity.ts#L22-L23) so we shouldn't rely on that for the `memoize` cache key. Using `id` should work though:
```suggestion
    normalizer: (args: [region: IRegionConfig]) => JSON.stringify(args[0].id)
```

File: src/client/api.ts [hunk 3]
```diff
@@ -403,6 +405,16 @@ export async function fetchOrganizationFeaturedProjects(
   });
 }
 
+export const fetchMemoizedStateBbox = memoize(
```
Comment (maurizi) [inline src/client/api.ts:408]: Great use of `memoize` here 💡

**Review by maurizi — CHANGES_REQUESTED** [review]
Just a few small cleanups, but I tested this and it's working well

**Review by maurizi — APPROVED** [review]
