### PR TITLE
Set keep-alive timeout higher than ALB idle timeout

### LINKED ISSUE #428: Resolve 502 errors generated by ELB
## Overview
We're seeing `502 Bad Gateway` errors crop up inconsistently in both staging and production. We need to figure out and address the source of these errors, since they are user-facing.

There are no application logs or Rollbar items being created, and the source of the error is likely infrastructural rather than solely at the application level.

## Supporting Evidence
- Our [CloudWatch logs](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(metrics~(~(~'AWS*2fApplicationELB~'HTTPCode_ELB_502_Count~'LoadBalancer~'app*2falbStagingApp*2f5a0ddc7dc30ea04e)~(~'.~'HTTPCode_Target_5XX_Count~'.~'.))~view~'timeSeries~stacked~false~region~'us-east-1~start~'2020-09-11T16*3a15*3a00.999Z~end~'2020-09-11T16*3a45*3a00.000Z~stat~'Sum~period~60);query=~'*7bAWS*2fApplicationELB*2cLoadBalancer*7d) confirm that the 502s were generated by the ELB, rather than the target application. [This significantly narrows down the things that could have happened](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-502-issues).
- These 502s do not appear to correspond to any other notable events within the application or its infrastructure, and I am unable to reproduce the issue. It definitely happened, I see it in the metrics, but I suspect that there may be a significant non-deterministic aspect to this.
- Nothing seems amiss at all within the NestJS application logs, and healthchecks were passing normally. It appears that the problem was limited to the requests in question.

## Additional Notes
Of all of the possible reasons for the 502 error, a common and subtle offender seems to be issues with the `KeepAlive` timeout differing between the application server and the ELB. There's a little more detail on this [here](https://shuheikagawa.com/blog/2019/04/25/keep-alive-timeout/) and [here](https://medium.com/@liquidgecka/a-tale-of-unexpected-elb-behavior-5281db9e5cb4). We have little direct evidence to support this assumption, but I see enough common factors with Shuhei Kagawa's post (using Express under the hood, putting it behind an ELB, relying on default values) that I think it's possible.

See [this Slack thread](https://azavea.slack.com/archives/C6UD5FG3T/p1599856048300400?thread_ts=1599842809.271200&cid=C6UD5FG3T) for additional context.

### PR DESCRIPTION
**Pull request by rbreslow**
## Overview

> Keep-alive, when enabled, enables the load balancer to reuse back-end connections until the keep-alive timeout expires. To ensure that the load balancer is responsible for closing the connections to your instance, make sure that the value you set for the HTTP keep-alive time is greater than the idle timeout setting configured for your load balancer.

The [default keep-alive timeout](https://nodejs.org/api/http.html#http_server_keepalivetimeout) for the Node http.Server is 5 seconds. The [default idle timeout](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#idle_timeout) for the ALB is 60 seconds. 

The ALB is opening connections for reuse, the Node http.Server closes that connection, and then the ALB tries to communicate over the closed connection which triggers a 502.

> **HTTP 502: Bad gateway**
>
> Possible causes:
> . . .
> The target closed the connection with a TCP RST or a TCP FIN while the load balancer had an outstanding request to the target. Check whether the keep-alive duration of the target is shorter than the idle timeout value of the load balancer.

We can see more evidence of this by looking at the ALB access logs with Athena:

<details>   
<summary>Details</summary>    

```sql
SELECT elb_status_code,
         request_processing_time,
         target_processing_time,
         response_processing_time,
         request_url
FROM stg_alb_logs
WHERE elb_status_code LIKE '5%';
```

Athena 2020-09-23 14-35-24

</details>

> `response_processing_time` is set to -1 if the load balancer can't send the request to a target. This can happen if the target closes the connection before the idle timeout or if the client sends a malformed request.

This PR sets the keep-alive timeout to be higher than the ALB timeout so that the ALB is responsible for prompting the closure of individual TCP connections to the server.

See:
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-502-issues
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-syntax
- https://adamcrowder.net/posts/node-express-api-and-aws-alb-502/ (Excellent deep dive into the problem)

Resolves #428 

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

I'm not sure how to replicate the failures we saw earlier. I've tried exercising the staging application and wasn't able to generate any 502s today before or after applying the fix (see the [Jenkins deploy](http://urbanappsci.internal.azavea.com/job/PublicMapping/job/districtbuilder/job/test%252Fjrb%252Fadjust-timeouts/2/console)). Additionally, the `prd_alb_logs` table in Athena does not contain any 502s.

I think the evidence makes it clear we should apply this either way, and we can be on the look out for more 502s as we're able to gather more data.

### CODE REVIEW

File: src/server/src/main.ts [hunk 1]
```diff
@@ -17,6 +17,16 @@ async function bootstrap(): Promise<void> {
...
+  // Save the output of 'listen' to a variable, which is a Node http.Server
+  const server = await app.listen(3005);
+
+  // Ensure all inactive connections are terminated by the ALB, by setting this
+  // a few seconds higher than the ALB idle timeout
+  server.keepAliveTimeout = 65000;
+
+  // Ensure the headersTimeout is set higher than the keepAliveTimeout due to
+  // this nodejs regression bug: https://github.com/nodejs/node/issues/27363
+  server.headersTimeout = 66000;
```
Comment (rbreslow) [inline src/server/src/main.ts:30]: This was resolved and back ported to Node v12 in https://github.com/nodejs/node/pull/34131. However, it doesn't look like the fix will be accessible until Node v12.18.5 drops (https://github.com/nodejs/node/commits/v12.x. vs https://github.com/nodejs/node/commits/v12.x-staging).

**Review by hectcastro — APPROVED** [review]
The application server timeout changes appear to be working as an effective 502 deterrent. I added a simple `k6` load test in 4827e9a32638b1aa6229d81e3387bcc473eaa875 and used it against an instance of the application with and without the changes.

When the timeout changes were not applied, 502s were present in the Athena ALB request logs. When the timeout changes were applied, 502s were not present in the logs. 👍
