### PR TITLE
Fix displaying map labels when option is unselected

### LINKED ISSUE #215: Deselecting label shows curly braces
## Description
If you select a label and then deselect, you see curly braces instead of nothing at all.

## Steps To Reproduce
1. Go to the map page for any project
1. Select any label
1. Select the first empty, option

## Expected behavior
No labels are shown on the map

## Actual behavior
Curly braces are shown where the labels were

## Screenshots
db_label_bug

### PR DESCRIPTION
**Pull request by maurizi**
Also switches to display the correct labels for the selected geounit, instead of always using the county labels, fixing a `TODO`.

Closes #215

### CODE REVIEW

File: src/client/components/map/Map.tsx [hunk 1]
```diff
@@ -159,12 +159,18 @@ const Map = ({
...
+        map.setLayoutProperty(`${geoLevel.id}-label`, "visibility", "none")
+      );
+    map && map.setLayoutProperty(`${selectedGeolevel.id}-label`, "visibility", "visible");
+    map &&
+      map.setLayoutProperty(
+        `${selectedGeolevel.id}-label`,
+        "text-field",
+        label ? `{${label}}` : ""
+      );
+  }, [map, label, geoLevelIndex]);
```
Comment (pcaisse) [inline src/client/components/map/Map.tsx:173]: One small change here to make the warnings go away:

```suggestion
  }, [map, label, staticMetadata, selectedGeolevel]);
```
